// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW4sVdTJFFuRlQPgP1lASm69gqWiku-II',
    appId: '1:433551615246:web:ed6937fa29295bb578e35f',
    messagingSenderId: '433551615246',
    projectId: 'gestao-academica-757ff',
    authDomain: 'gestao-academica-757ff.firebaseapp.com',
    storageBucket: 'gestao-academica-757ff.firebasestorage.app',
    measurementId: 'G-99XSFXSFJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbtPcWgLOpyiyXeIbMcNPRrkNTvu_toBg',
    appId: '1:433551615246:android:7195295c5ea77cc678e35f',
    messagingSenderId: '433551615246',
    projectId: 'gestao-academica-757ff',
    storageBucket: 'gestao-academica-757ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf55_chpeC2Yq5ZR4T92ov6vVd_i477UA',
    appId: '1:433551615246:ios:233ffa3353dae85578e35f',
    messagingSenderId: '433551615246',
    projectId: 'gestao-academica-757ff',
    storageBucket: 'gestao-academica-757ff.firebasestorage.app',
    iosBundleId: 'com.example.academicManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf55_chpeC2Yq5ZR4T92ov6vVd_i477UA',
    appId: '1:433551615246:ios:233ffa3353dae85578e35f',
    messagingSenderId: '433551615246',
    projectId: 'gestao-academica-757ff',
    storageBucket: 'gestao-academica-757ff.firebasestorage.app',
    iosBundleId: 'com.example.academicManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW4sVdTJFFuRlQPgP1lASm69gqWiku-II',
    appId: '1:433551615246:web:2b14b2d88052002d78e35f',
    messagingSenderId: '433551615246',
    projectId: 'gestao-academica-757ff',
    authDomain: 'gestao-academica-757ff.firebaseapp.com',
    storageBucket: 'gestao-academica-757ff.firebasestorage.app',
    measurementId: 'G-LY0TG75363',
  );
}
